export function findingsToComplianceMarkdown(findings, profiles) {
  const effectiveProfiles = profiles?.length > 0 ? profiles : null;
  const byFramework = {};
  const byControl = {};

  for (const finding of findings) {
    const mappings = finding.complianceMapping ?? [];
    if (mappings.length === 0) {
      const uncategorized = byFramework["Uncategorized"] ?? {};
      const uncategorizedControls = uncategorized["—"] ?? [];
      uncategorizedControls.push(finding);
      byFramework["Uncategorized"] = uncategorized;
      byFramework["Uncategorized"]["—"] = uncategorizedControls;
      continue;
    }
    for (const mapping of mappings) {
      if (effectiveProfiles && !effectiveProfiles.includes(mapping.framework)) continue;
      const fw = byFramework[mapping.framework] ?? {};
      const ctrl = fw[mapping.control] ?? [];
      ctrl.push(finding);
      fw[mapping.control] = ctrl;
      byFramework[mapping.framework] = fw;
      const key = `${mapping.framework}::${mapping.control}`;
      byControl[key] = byControl[key] ?? { framework: mapping.framework, control: mapping.control, title: mapping.title, findings: [] };
      byControl[key].findings.push(finding);
    }
  }

  const lines = ["# Compliance Report", ""];

  const frameworks = Object.keys(byFramework).sort();
  for (const framework of frameworks) {
    lines.push(`## ${framework}`, "");
    const controls = byFramework[framework];
    const controlIds = Object.keys(controls).sort();
    for (const controlId of controlIds) {
      const key = `${framework}::${controlId}`;
      const entry = byControl[key];
      const findingsForControl = controls[controlId];
      lines.push(`### ${controlId} — ${entry?.title ?? "Uncategorized"}`, "");
      for (const f of findingsForControl) {
        lines.push(`- **[${f.severity.toUpperCase()}]** ${f.title} — ${f.files.join(", ")}`);
        if (f.explanation) {
          lines.push(`  ${f.explanation}`);
        }
      }
      lines.push("");
    }
  }

  if (findings.length === 0) {
    lines.push("No compliance findings.");
  }

  lines.push("", "---", `Generated by security-review-commons | ${findings.length} finding(s) | Profiles: ${effectiveProfiles ? effectiveProfiles.join(", ") : "all"}`);
  return lines.join("\n");
}

export function findingsToComplianceJson(findings, profiles) {
  const effectiveProfiles = profiles?.length > 0 ? profiles : null;
  const byFramework = {};

  for (const finding of findings) {
    const mappings = finding.complianceMapping ?? [];
    if (mappings.length === 0) {
      const uncategorized = byFramework["Uncategorized"] ?? { framework: "Uncategorized", controls: {} };
      const ctrl = uncategorized.controls["—"] ?? [];
      ctrl.push({
        id: finding.id,
        title: finding.title,
        severity: finding.severity,
        category: finding.category,
        files: finding.files,
        detectionMethod: finding.detectionMethod ?? "pattern"
      });
      byFramework["Uncategorized"] = uncategorized;
      continue;
    }
    for (const mapping of mappings) {
      if (effectiveProfiles && !effectiveProfiles.includes(mapping.framework)) continue;
      const fw = byFramework[mapping.framework] ?? { framework: mapping.framework, controls: {} };
      const ctrl = fw.controls[mapping.control] ?? {
        control: mapping.control,
        title: mapping.title,
        severity: mapping.severity,
        findings: []
      };
      ctrl.findings.push({
        id: finding.id,
        title: finding.title,
        severity: finding.severity,
        category: finding.category,
        files: finding.files,
        detectionMethod: finding.detectionMethod ?? "pattern"
      });
      fw.controls[mapping.control] = ctrl;
      byFramework[mapping.framework] = fw;
    }
  }

  return {
    profiles: effectiveProfiles ?? "all",
    totalFindings: findings.length,
    frameworks: Object.values(byFramework).map((fw) => ({
      ...fw,
      controls: Object.values(fw.controls ?? {})
    }))
  };
}